"""Stdlib modules the downloaded engine (torch / librosa) imports at load time.

The slim PyInstaller bundle only ships what Analysis sees. Torch then loads
from Application Support and does ``from timeit import default_timer``. If
that module is missing from the frozen interpreter, every split fails.
"""

ENGINE_STDLIB = (
    "argparse",
    "ast",
    "asyncio",
    "base64",
    "bisect",
    "bz2",
    "calendar",
    "cmath",
    "concurrent",
    "concurrent.futures",
    "contextvars",
    "copy",
    "csv",
    "ctypes",
    "dataclasses",
    "datetime",
    "difflib",
    "dis",
    "email",
    "fileinput",
    "gettext",
    "glob",
    "gzip",
    "hashlib",
    "heapq",
    "http",
    "importlib",
    "inspect",
    "json",
    "linecache",
    "locale",
    "logging",
    "lzma",
    "multiprocessing",
    "numbers",
    "opcode",
    "pickle",
    "pickletools",
    "platform",
    "pprint",
    "queue",
    "quopri",
    "random",
    "runpy",
    "selectors",
    "shutil",
    "signal",
    "socket",
    "ssl",
    "string",
    "struct",
    "subprocess",
    "sysconfig",
    "tarfile",
    "tempfile",
    "textwrap",
    "threading",
    "timeit",
    "token",
    "tokenize",
    "traceback",
    "unittest",
    "unittest.mock",
    "urllib",
    "uuid",
    "zipfile",
)
